table Code_Helper_2016-17
	isHidden
	lineageTag: 4200f66c-3c40-485d-90c8-64f7c329691f

	column Code
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 07c2106f-3aa0-43c9-bc22-699816a8f4a8
		summarizeBy: count
		sourceColumn: Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Industry
		dataType: string
		isHidden
		lineageTag: 2e8af6ba-09fc-4d47-a736-7d44cfdbe659
		summarizeBy: none
		sourceColumn: Industry

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Code_Helper_2016-17 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Mitch\Desktop\Input output\Table 5 16-17.xlsx"), null, true),
				    #"Table 5_Sheet" = Source{[Item="Table 5",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(#"Table 5_Sheet",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Removed Top Rows1" = Table.Skip(#"Promoted Headers",1),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Top Rows1",{{"Column2", "Industry"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each [Industry] <> null),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Filtered Rows",16),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Bottom Rows",{"Column127", "Column128", "Column129", "Column130", "Column131", "Column132", "Column133", "Column134", "Column135", "Column136", "Column137", "Column138", "Column139", "Column140", "Column141", "Column142", "Column143", "Column144", "Column145", "Column146", "Column147", "Column148", "Column149", "Column150", "Column151", "Column152", "Column153", "Column154", "Column155", "Column156", "Column157", "Column158", "Column159", "Column160", "Column161", "Column162", "Column163", "Column164", "Column165", "Column166", "Column167", "Column168", "Column169", "Column170", "Column171", "Column172", "Column173", "Column174", "Column175", "Column176", "Column177", "Column178", "Column179", "Column180", "Column181", "Column182", "Column183", "Column184", "Column185", "Column186", "Column187", "Column188", "Column189", "Column190", "Column191", "Column192", "Column193", "Column194", "Column195", "Column196", "Column197", "Column198", "Column199", "Column200", "Column201", "Column202", "Column203", "Column204", "Column205", "Column206", "Column207", "Column208", "Column209", "Column210", "Column211", "Column212", "Column213", "Column214", "Column215", "Column216", "Column217", "Column218", "Column219", "Column220", "Column221", "Column222", "Column223", "Column224", "Column225", "Column226", "Column227", "Column228", "Column229", "Column230", "Column231", "Column232", "Column233", "Column234", "Column235", "Column236", "Column237", "Column238", "Column239", "Column240", "Column241", "Column242", "Column243", "Column244", "Column245", "Column246", "Column247", "Column248", "Column249", "Column250", "Column251", "Column252", "Column253", "Column254", "Column255", "Column256", "Total Industry Uses", "Final Uses#(lf)(Q1 to Q7)", "Total Supply"}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Removed Columns", {"Column1", "Industry"}, "Attribute", "Value"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Flow to Industry"}, {"Value", "$"}, {"Column1", "Code"}}),
				    #"Multiplied Column" = Table.TransformColumns(#"Renamed Columns1", {{"$", each _ * 1000000, type number}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Multiplied Column",{{"$", "Value"}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Renamed Columns2",{{"Industry", Text.Proper, type text}, {"Flow to Industry", Text.Proper, type text}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Capitalized Each Word",{{"Code", Int64.Type}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"Industry"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Removed Duplicates",{"Value", "Flow to Industry"})
				in
				    #"Removed Columns1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

