table Dim_Industry
	lineageTag: dc5cbdc0-7983-48be-b49f-1d0989dbc74d

	column Industry
		dataType: string
		lineageTag: 67121c53-6e7a-4ad1-bc16-912bfa24a9ec
		summarizeBy: none
		sourceColumn: Industry

		annotation SummarizationSetBy = Automatic

	column Code
		dataType: int64
		formatString: 0
		lineageTag: 51ab4004-e7da-4ca1-85a6-d48635ad8d46
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	partition Dim_Industry = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Mitch\Desktop\Input output\Table 5 21-22.xlsx"), null, true),
				    #"Table 5_Sheet" = Source{[Item="Table 5",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(#"Table 5_Sheet",2),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"TABLE 5. INDUSTRY BY INDUSTRY FLOW TABLE (DIRECT ALLOCATION OF IMPORTS)", "Industry"}}),
				    #"Removed Top Rows1" = Table.Skip(#"Renamed Columns",1),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Top Rows1", each [Industry] <> null),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Filtered Rows",16),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Bottom Rows",{"Total Industry Uses", "Column128", "Column129", "Column130", "Column131", "Column132", "Column133", "Column134", "Column135", "Column136", "Column137", "Column138", "Column139", "Column140", "Column141", "Column142", "Column143", "Column144", "Column145", "Column146", "Column147", "Column148", "Column149", "Column150", "Column151", "Column152", "Column153", "Column154", "Column155", "Column156", "Column157", "Column158", "Column159", "Column160", "Column161", "Column162", "Column163", "Column164", "Column165", "Column166", "Column167", "Column168", "Column169", "Column170", "Column171", "Column172", "Column173", "Column174", "Column175", "Column176", "Column177", "Column178", "Column179", "Column180", "Column181", "Column182", "Column183", "Column184", "Column185", "Column186", "Column187", "Column188", "Column189", "Column190", "Column191", "Column192", "Column193", "Column194", "Column195", "Column196", "Column197", "Column198", "Column199", "Column200", "Column201", "Column202", "Column203", "Column204", "Column205", "Column206", "Column207", "Column208", "Column209", "Column210", "Column211", "Column212", "Column213", "Column214", "Column215", "Column216", "Column217", "Column218", "Column219", "Column220", "Column221", "Column222", "Column223", "Column224", "Column225", "Column226", "Column227", "Column228", "Column229", "Column230", "Column231", "Column232", "Column233", "Column234", "Column235", "Column236", "Column237", "Column238", "Column239", "Column240", "Column241", "Column242", "Column243", "Column244", "Column245", "Column246", "Column247", "Column248", "Column249", "Column250", "Column251", "Column252", "Column253", "Column254", "Column255", "Column256", "Final Uses #(lf)(Q1 to Q7)", "Total Supply"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Removed Duplicates",{{"Industry", Text.Proper, type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Capitalized Each Word",{"Industry", "Column1"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Other Columns",{{"Column1", "Code"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Code", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

