table 'Fact Input_2016-17'
	lineageTag: d62eda0c-5c22-45a5-9cd9-c749ccb54cbb

	column Industry
		dataType: string
		lineageTag: 3c92a3e5-fc76-4f11-8cbf-12928cee013a
		summarizeBy: none
		sourceColumn: Industry

		annotation SummarizationSetBy = Automatic

	column 'Total Intermediate Use'
		dataType: string
		lineageTag: 93e45b89-8136-4b78-956d-08aff88e383c
		summarizeBy: none
		sourceColumn: Total Intermediate Use

		annotation SummarizationSetBy = Automatic

	column 'Compensation of employees'
		dataType: string
		lineageTag: 11aa0fb6-402f-4104-995a-b4770939ebac
		summarizeBy: none
		sourceColumn: Compensation of employees

		annotation SummarizationSetBy = Automatic

	column 'Gross operating surplus & mixed income'
		dataType: string
		lineageTag: f1d0ac75-d7f0-4a4d-954c-70106ee92d08
		summarizeBy: none
		sourceColumn: Gross operating surplus & mixed income

		annotation SummarizationSetBy = Automatic

	column 'Taxes less subsidies on products'
		dataType: string
		lineageTag: 3840b9cb-e57b-4f10-9281-02a690307303
		summarizeBy: none
		sourceColumn: Taxes less subsidies on products

		annotation SummarizationSetBy = Automatic

	column 'Other taxes less subsidies on production'
		dataType: string
		lineageTag: 3c59631b-dc98-43d9-a329-1451e239d625
		summarizeBy: none
		sourceColumn: Other taxes less subsidies on production

		annotation SummarizationSetBy = Automatic

	column 'Complementary imports'
		dataType: string
		lineageTag: 285535ce-4bfd-415e-baed-6777173b925d
		summarizeBy: none
		sourceColumn: Complementary imports

		annotation SummarizationSetBy = Automatic

	column Imports
		dataType: double
		lineageTag: e8c7c21e-7403-4fbf-987a-f65340b56304
		summarizeBy: sum
		sourceColumn: Imports

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Australian Production'
		dataType: double
		lineageTag: 188baa47-9e9b-429d-a4e6-303ec07d504f
		summarizeBy: sum
		sourceColumn: Australian Production

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Value Added'
		dataType: double
		lineageTag: 8a998ea3-1f56-4f1e-a848-174a4cb1a6c1
		summarizeBy: sum
		sourceColumn: Value Added

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Code
		dataType: int64
		formatString: 0
		lineageTag: c2c45651-fc8a-446e-ac28-1debf1934281
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	partition 'Fact Input_2016-17' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Mitch\Desktop\Input output\Table 5 16-17.xlsx"), null, true),
				    #"Table 5_Sheet" = Source{[Item="Table 5",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(#"Table 5_Sheet",1),
				    #"Filtered Rows4" = Table.SelectRows(#"Removed Top Rows", each [Column2] <> ""),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Filtered Rows4", [PromoteAllScalars=true]),
				    #"Renamed Columns3" = Table.RenameColumns(#"Promoted Headers1",{{"Column2", "Industry"}}),
				    #"Demoted Headers" = Table.DemoteHeaders(#"Renamed Columns3"),
				    #"Filtered Rows" = Table.SelectRows(#"Demoted Headers", each [Column2] <> null),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Column118", "Column119", "Column120", "Column121", "Column122", "Column123", "Column124", "Column125", "Column126", "Column127", "Column128", "Column129", "Column130", "Column131", "Column132", "Column133", "Column134", "Column135", "Column136", "Column137", "Column138", "Column139", "Column140", "Column141", "Column142", "Column143", "Column144", "Column145", "Column146", "Column147", "Column148", "Column149", "Column150", "Column151", "Column152", "Column153", "Column154", "Column155", "Column156", "Column157", "Column158", "Column159", "Column160", "Column161", "Column162", "Column163", "Column164", "Column165", "Column166", "Column167", "Column168", "Column169", "Column170", "Column171", "Column172", "Column173", "Column174", "Column175", "Column176", "Column177", "Column178", "Column179", "Column180", "Column181", "Column182", "Column183", "Column184", "Column185", "Column186", "Column187", "Column188", "Column189", "Column190", "Column191", "Column192", "Column193", "Column194", "Column195", "Column196", "Column197", "Column198", "Column199", "Column200", "Column201", "Column202", "Column203", "Column204", "Column205", "Column206", "Column207", "Column208", "Column209", "Column210", "Column211", "Column212", "Column213", "Column214", "Column215", "Column216", "Column217", "Column218", "Column219", "Column220", "Column221", "Column222", "Column223", "Column224", "Column225", "Column226", "Column227", "Column228", "Column229", "Column230", "Column231", "Column232", "Column233", "Column234", "Column235", "Column236", "Column237", "Column238", "Column239", "Column240", "Column241", "Column242", "Column243", "Column244", "Column245", "Column246", "Column247", "Column248", "Column249", "Column250", "Column251", "Column252", "Column253", "Column254", "Column255", "Column256", "Column1"}),
				    #"Transposed Table" = Table.Transpose(#"Removed Columns"),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Transposed Table", [PromoteAllScalars=true]),
				    #"Filtered Rows1" = Table.SelectRows(#"Promoted Headers", each [Industry] <> "Total Industry Uses"),
				    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows1",{"© Commonwealth of Australia 2019", "Sheep, Grains, Beef and Dairy Cattle", "Poultry and Other Livestock", "Other Agriculture", "Aquaculture", "Forestry and Logging", "Fishing, hunting and trapping", "Agriculture, Forestry and Fishing Support Services", "Coal Mining", "Oil and Gas Extraction", "Iron Ore Mining", "Non Ferrous Metal Ore Mining", "Non Metallic Mineral Mining", "Exploration and Mining Support Services", "Meat and Meat Product Manufacturing", "Processed Seafood Manufacturing", "Dairy Product Manufacturing", "Fruit and Vegetable Product Manufacturing", "Oils and Fats Manufacturing", "Grain Mill and Cereal Product Manufacturing", "Bakery Product Manufacturing", "Sugar and Confectionery Manufacturing", "Other Food Product Manufacturing", "Soft Drinks, Cordials and Syrup Manufacturing", "Beer Manufacturing", "Wine, Spirits and Tobacco", "Textile Manufacturing", "Tanned Leather, Dressed Fur and Leather Product Manufacturing", "Textile Product Manufacturing", "Knitted Product Manufacturing", "Clothing Manufacturing", "Footwear Manufacturing", "Sawmill Product Manufacturing", "Other Wood Product Manufacturing", "Pulp, Paper and Paperboard Manufacturing", "Paper Stationery and Other Converted Paper Product Manufacturing", "Printing (including the Reproduction of Recorded Media)", "Petroleum and Coal Product Manufacturing", "Human Pharmaceutical and Medicinal Product Manufacturing", "Veterinary Pharmaceutical and Medicinal Product Manufacturing", "Basic Chemical Manufacturing", "Cleaning Compounds and Toiletry Preparation Manufacturing", "Polymer Product Manufacturing", "Natural Rubber Product Manufacturing", "Glass and Glass Product Manufacturing", "Ceramic Product Manufacturing", "Cement, Lime and Ready-Mixed Concrete Manufacturing", "Plaster and Concrete Product Manufacturing", "Other Non-Metallic Mineral Product Manufacturing", "Iron and Steel Manufacturing", "Basic Non-Ferrous Metal Manufacturing", "Forged Iron and Steel Product Manufacturing", "Structural Metal Product Manufacturing", "Metal Containers and Other Sheet Metal Product Manufacturing", "Other Fabricated Metal Product Manufacturing", "Motor Vehicles and Parts; Other Transport Equipment manufacturing", "Ships and Boat Manufacturing", "Railway Rolling Stock Manufacturing", "Aircraft Manufacturing", "Professional, Scientific, Computer and Electronic Equipment Manufacturing", "Electrical Equipment Manufacturing", "Domestic Appliance Manufacturing", "Specialised and Other Machinery and Equipment Manufacturing", "Furniture Manufacturing", "Other Manufactured Products", "Electricity Generation", "Electricity Transmission, Distribution, On Selling and Electricity Market Operation", "Gas Supply", "Water Supply, Sewerage and Drainage Services", "Waste Collection, Treatment and Disposal Services", "Residential Building Construction", "Non-Residential Building Construction", "Heavy and Civil Engineering Construction", "Construction Services", "Wholesale Trade", "Retail Trade", "Accommodation", "Food and Beverage Services", "Road Transport", "Rail Transport", "Water, Pipeline and Other Transport", "Air and Space Transport", "Postal and Courier Pick-up and Delivery Service", "Transport Support Services and Storage", "Publishing (except Internet and Music Publishing)", "Motion Picture and Sound Recording", "Broadcasting (except Internet)", "Internet Service Providers, Internet Publishing and Broadcasting, Websearch Portals and Data Processing", "Telecommunication Services", "Library and Other Information Services", "Finance", "Insurance and Superannuation Funds", "Auxiliary Finance and Insurance Services", "Rental and Hiring Services (except Real Estate)", "Ownership of Dwellings", "Non-Residential Property Operators and Real Estate Services", "Professional, Scientific and Technical Services", "Computer Systems Design and Related Services", "Employment, Travel Agency and Other Administrative Services", "Building Cleaning, Pest Control and Other Support Services", "Public Administration and Regulatory Services", "Defence", "Public Order and Safety", "Primary and Secondary Education Services (including Pre-Schools and Special Schools)", "Technical, Vocational and Tertiary Education Services (including Undergraduate and Postgraduate)", "Arts, Sports, Adult and Other Education Services (including Community Education)", "Health Care Services", "Residential Care and Social Assistance Services", "Heritage, Creative and Performing Arts", "Sports and Recreation", "Gambling", "Automotive Repair and Maintenance", "Other Repair and Maintenance", "Personal Services", "Other Services"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"Competing imports", "Imports"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns",{"Gross Domestic Product"}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Removed Columns2",{{"Industry", Text.Proper, type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Capitalized Each Word", {"Industry"}, #"Code_Helper_2016-17", {"Industry"}, "Code_Helper_2016-17", JoinKind.LeftOuter),
				    #"Expanded Code_Helper_2016-17" = Table.ExpandTableColumn(#"Merged Queries", "Code_Helper_2016-17", {"Code"}, {"Code"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Code_Helper_2016-17",{{"Imports", type number}, {"Value Added", type number}, {"Australian Production", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

