table Fact_Output_Unpivot_2016-17
	lineageTag: 2ffeec2f-51a6-4d12-bc9f-58d0347b32a3

	column Industry
		dataType: string
		lineageTag: 3b2e77d9-8555-47d5-b98e-90405e441109
		summarizeBy: none
		sourceColumn: Industry

		annotation SummarizationSetBy = Automatic

	column 'Flow to Industry'
		dataType: string
		lineageTag: 8f8c114c-509f-411f-a981-9c0482a0a85f
		summarizeBy: none
		sourceColumn: Flow to Industry

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: b24491e9-4997-4ff1-95da-ad7b6f63ffb2
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Code
		dataType: int64
		formatString: 0
		lineageTag: 1e22ca45-b2cf-480c-8561-06e6e600fe2a
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	partition Fact_Output_Unpivot_2016-17 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Mitch\Desktop\Input output\Table 5 16-17.xlsx"), null, true),
				    #"Table 5_Sheet" = Source{[Item="Table 5",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(#"Table 5_Sheet",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Removed Top Rows1" = Table.Skip(#"Promoted Headers",1),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Top Rows1",{{"Column2", "Industry"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each [Industry] <> null),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Filtered Rows",16),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Bottom Rows",{"Column127", "Column128", "Column129", "Column130", "Column131", "Column132", "Column133", "Column134", "Column135", "Column136", "Column137", "Column138", "Column139", "Column140", "Column141", "Column142", "Column143", "Column144", "Column145", "Column146", "Column147", "Column148", "Column149", "Column150", "Column151", "Column152", "Column153", "Column154", "Column155", "Column156", "Column157", "Column158", "Column159", "Column160", "Column161", "Column162", "Column163", "Column164", "Column165", "Column166", "Column167", "Column168", "Column169", "Column170", "Column171", "Column172", "Column173", "Column174", "Column175", "Column176", "Column177", "Column178", "Column179", "Column180", "Column181", "Column182", "Column183", "Column184", "Column185", "Column186", "Column187", "Column188", "Column189", "Column190", "Column191", "Column192", "Column193", "Column194", "Column195", "Column196", "Column197", "Column198", "Column199", "Column200", "Column201", "Column202", "Column203", "Column204", "Column205", "Column206", "Column207", "Column208", "Column209", "Column210", "Column211", "Column212", "Column213", "Column214", "Column215", "Column216", "Column217", "Column218", "Column219", "Column220", "Column221", "Column222", "Column223", "Column224", "Column225", "Column226", "Column227", "Column228", "Column229", "Column230", "Column231", "Column232", "Column233", "Column234", "Column235", "Column236", "Column237", "Column238", "Column239", "Column240", "Column241", "Column242", "Column243", "Column244", "Column245", "Column246", "Column247", "Column248", "Column249", "Column250", "Column251", "Column252", "Column253", "Column254", "Column255", "Column256", "Total Industry Uses", "Final Uses#(lf)(Q1 to Q7)", "Total Supply"}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Removed Columns", {"Column1", "Industry"}, "Attribute", "Value"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Flow to Industry"}, {"Value", "$"}, {"Column1", "Code"}}),
				    #"Multiplied Column" = Table.TransformColumns(#"Renamed Columns1", {{"$", each _ * 1000000, type number}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Multiplied Column",{{"$", "Value"}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Renamed Columns2",{{"Industry", Text.Proper, type text}, {"Flow to Industry", Text.Proper, type text}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Capitalized Each Word",{{"Code", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

